### ISSUE TITLE
How to login?

### ISSUE THREAD

**Issue by vdemichev** [alitrack/superset_app#2]
Thanks for porting to Windows!
I launch it with ./python app.py run. Then go to http://127.0.0.1:5000/login/ and see a login window. What next? Login/pwd admin/admin does not work.

**Comment by alitrack** [comment]
```python
MIRROR = "https://mirrors.aliyun.com/pypi/simple/"
PASSWORD ='qwert'
USERNAME = 'admin'
FIRSTNAME = 'Steven'
LASTNAME = 'Li'  
EMAIL = 'admin@fab.org'
PORT = 8088 
SUPERSET_VER='2.1.0'
```

**Comment by vdemichev** [comment]
Thank you, works! Btw, part of the menu still in Chinese, even when set to English.

**Comment by alitrack** [comment]
just delete `superset_config_ex.py` and restart your app.

**Comment by vdemichev** [comment]
Thank you!
