### ISSUE TITLE
Error during the installation

### ISSUE THREAD

**Issue by nsrivastava2** [alitrack/superset_app#3]
This is really wonderful application if it works. 
Please find below the error being reported while installing the Portable Version of Apache Superset. Please help. 

`
          self.filelist.extend(build_ext.get_source_files())
        File "<string>", line 201, in get_source_files
        File "C:\Users\hp\AppData\Local\Temp\pip-build-env-bx_ipgki\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Traceback (most recent call last):
  File "C:\Users\hp\Downloads\python-3.10.11-embed-amd64\install.py", line 159, in <module>
    install_requirements()
  File "C:\Users\hp\Downloads\python-3.10.11-embed-amd64\install.py", line 155, in install_requirements
    install(["-r","requirements.txt"])
  File "C:\Users\hp\Downloads\python-3.10.11-embed-amd64\install.py", line 123, in install
    subprocess.check_call([sys.executable, '-m', 'pip', 'install']+pkgs +['-i', MIRROR])
  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\hp\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', '-m', 'pip', 'install', '-r', 'requirements.txt', '-i', 'https://mirrors.aliyun.com/pypi/simple/']' returned non-zero exit status 1.`

**Comment by alitrack** [comment]
from the error log, seems you did  not use [python-3.10.11-embed-amd64.zip](https://www.python.org/ftp/python/3.10.11/python-3.10.11-embed-amd64.zip)

make sure you use the python.exe from python-3.10.11-embed-amd64

**Comment by nsrivastava2** [comment]
Thank you. I tried that and the installation seems to have completed. Now I am not sure what command to run to be able to start Superset and on which port.

**Comment by nsrivastava2** [comment]
It worked. To run the application I had to double click the run.Bat file available in the root folder itself. 

Now the URL: http://127.0.0.1:8088/login/ is opening but I am not able to login. Default admin/admin is not working.

**Comment by alitrack** [comment]
user admin
password qwert

**Comment by nsrivastava2** [comment]
Thanks a lot. It worked. Now I am facing another issue and that is with the translation. Seems like English and Chinese have got mingled up. 
Screenshot:
https://www.dropbox.com/scl/fi/h66p2lfyiag3s6dy5qmwv/Screenshot-2023-08-24-175259.png?rlkey=2ascfjzuzgs4wjcqadd84mq6r&dl=0

**Comment by alitrack** [comment]
just delete `superset_config_ex.py` and restart your app.

**Comment by nsrivastava2** [comment]
Awesome. That solved the issue. Thanks a lot. I will prepare a User Manual explaining the steps and the challenges and you may include the same in the README file. That might be of help for the people looking to use this application
